### ISSUE TITLE
Question: How to debug 'languageDefinition is not a function'

### ISSUE THREAD

**Issue by esmasth** [valeriangalliat/markdown-it-highlightjs#35]
I have been trying to use `markdown-it-highlightjs` via a vscode markdown extension along with a 3rd party highlightjs grammar.

```ts
import type MarkdownIt from 'markdown-it';
export function activate(context: vscode.ExtensionContext) {
    return {
        extendMarkdownIt(mdi: MarkdownIt) {
            return mdi.use(require('markdown-it-highlightjs'), {
                register: {
                    yang: require('./highlightjs-yang')
                }
            });
        }
    };
}
```

and I hit the following errors in the debug console which I do not know where to begin debugging as as beginner. 

```
TypeError: languageDefinition is not a function
	at Object.registerLanguage (/home/esmasth/code/pyang-vscode/node_modules/highlight.js/lib/core.js:2402:14)
	at registerLangs (/home/esmasth/code/pyang-vscode/node_modules/markdown-it-highlightjs/dist/core.js:42:10)
	at core (/home/esmasth/code/pyang-vscode/node_modules/markdown-it-highlightjs/dist/core.js:112:5)
	at Function.highlightjs (/home/esmasth/code/pyang-vscode/node_modules/markdown-it-highlightjs/dist/index.js:47:26)
	at S.use (/home/esmasth/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/extensions/markdown-language-features/dist/extension.js:1:189621)
	at Object.extendMarkdownIt (/home/esmasth/code/pyang-vscode/src/extension.ts:143:24)
	at /home/esmasth/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/extensions/markdown-language-features/dist/extension.js:1:652598
	at /home/esmasth/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/extensions/markdown-language-features/dist/extension.js:1:647211
	at process.processTicksAndRejections (/home/esmasth/code/pyang-vscode/lib/internal/process/task_queues.js:95:5)
	at async t.MarkdownItEngine._getEngine (/home/esmasth/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/extensions/markdown-language-features/dist/extension.js:1:647659)
	at async t.MarkdownItEngine.render (/home/esmasth/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/extensions/markdown-language-features/dist/extension.js:1:648168)
	at async t.MdDocumentRenderer.renderBody (/home/esmasth/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/extensions/markdown-language-features/dist/extension.js:1:655918)
	at async t.MdDocumentRenderer.renderDocument (/home/esmasth/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/extensions/markdown-language-features/dist/extension.js:1:654845)
	at async d._updatePreview (/home/esmasth/.vscode-server/bin/38c31bc77e0dd6ae88a4e9cc93428cc27a56ba40/extensions/markdown-language-features/dist/extension.js:1:663092) {stack: 'TypeError: languageDefinition is not a functi…language-features/dist/extension.js:1:663092)', message: 'languageDefinition is not a function'}
```

**Comment by valeriangalliat** [comment]
Hey! Did you end up figuring this out?

If you still need help, it would be useful to know what version of `markdown-it`, `highlight.js` and `markdown-it-highlightjs` you use

Also it could be useful to have the output of `require('./highlightjs-yang')`

**Comment by esmasth** [comment]
Thanks, I'll get back soon with a retry
